---
jobs:
- name: deploy-concourse
  serial: true
  plan:
  - aggregate:
    - get: pipelines
      trigger: false
    - get: concourse-private
      trigger: true
    - get: concourse-release
      trigger: false
      params:
        globs:
          - concourse-*.tgz
          - garden-linux-*.tgz
    - get: concourse-config
      trigger: true
    - get: concourse-stemcell
      trigger: false
  - task: concourse-decrypt
    file: pipelines/tasks/decrypt.yml
    config:
      params:
        INPUT_FILE: concourse-private/concourse.yml
        OUTPUT_FILE: concourse.yml
        PASSPHRASE: {{concourse-private-passphrase}}
  - task: concourse-manifest
    file: pipelines/tasks/spiff-merge.yml
    config:
      params:
        OUTPUT_FILE: manifest.yml
        SOURCE_FILE: concourse-config/concourse/concourse.yml
        MERGE_FILES: concourse-decrypt/concourse.yml
  - put: concourse-deployment
    params:
      manifest: concourse-manifest/manifest.yml
      releases:
        - concourse-release/concourse-*.tgz
        - concourse-release/garden-linux-*.tgz
      stemcells:
        - concourse-stemcell/*.tgz

resources:
- name: pipelines
  type: git
  source:
    uri: {{pipelines-git-url}}
    branch: {{pipelines-branch}}

- name: concourse-private
  type: s3
  source:
    bucket: {{concourse-private-bucket}}
    versioned_file: {{concourse-private-manifest-file}}
    access_key_id: {{concourse-private-access-key-id}}
    secret_access_key: {{concourse-private-secret-access-key}}
    region-name: {{concourse-private-region-name}}
    private: true

- name: concourse-config
  type: git
  source:
    uri: {{concourse-config-git-url}}
    branch: {{concourse-config-git-branch}}

- name: concourse-stemcell
  type: bosh-io-stemcell
  source:
    name: {{concourse-stemcell}}

- name: concourse-release
  type: github-release
  source:
    repository: concourse
    user: concourse

- name: concourse-deployment
  type: bosh-deployment
  source:
    target: {{concourse-deployment-bosh-target}}
    username: {{concourse-deployment-bosh-username}}
    password: {{concourse-deployment-bosh-password}}
    deployment: {{concourse-deployment-bosh-deployment}}
    ignore_ssl: true
